### ISSUE TITLE
Add requirements.txt with required dependencies

### ISSUE THREAD

**Issue by kasparsd** [Mictronics/meshtastic2hass#1]
To simplify the usage of this package, add `requirements.txt` with all of the required package dependencies (per [docs](https://pip.pypa.io/en/stable/reference/requirements-file-format/)):

- paho-mqtt
- meshtastic
- pypubsub

Are there others?

**Comment by Mictronics** [comment]
Is this file required even when it builds as a package?

**Comment by kasparsd** [comment]
Good question. I don't have any experience with Python packaging or development so I had to google that. It appears that `install_requires` in `setup.cfg` are dependencies for _running_ the package while `requirements.txt` could be used for listing  development dependencies:

> install_requires defines the dependencies for a single project, [Requirements Files](https://pip.pypa.io/en/latest/user_guide/#requirements-files) are often used to define the requirements for a complete Python environment. Whereas install_requires requirements are minimal, requirements files often contain an exhaustive listing of pinned versions for the purpose of achieving [repeatable installations](https://pip.pypa.io/en/latest/topics/repeatable-installs/#repeatability) of a complete environment.

from https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/#requirements-files

So in case of this project it appears to have the following additional packages for linting and eventual testing (I understand this was probably added by the packaging boilerplate) -- flake8 and pytest:

https://github.com/Mictronics/meshtastic2hass/blob/8fd5165a8af5227737420095f79962ca17250822/.github/workflows/python-package.yml#L29-L31

so that all of those CI tests can be run locally.

**Comment by Mictronics** [comment]
Package successfully deployed on PyPI. So works without this file. Will close the issue and we will see. Reopen in case of future problems.
