### ISSUE TITLE
Document script arguments and usage in readme

### ISSUE THREAD

**Issue by kasparsd** [Mictronics/meshtastic2hass#2]
Use the readme in the project to document the following:

1. Script dependencies and install process.
2. Script usage and arguments.

The current help text reads:

```
usage: meshtastic2hass [-h] --dev DEV --mqtt-host MQTT_HOST
                       [--mqtt-port MQTT_PORT] --mqtt-user MQTT_USER
                       --mqtt-password MQTT_PASSWORD [--version]
```

**Comment by Mictronics** [comment]
Fixed with f5d264b4d73cd425e457d6cf9f9b780a245b0abb

**Comment by kasparsd** [comment]
Thanks for adding the docs! Happy to help out with pull requests as well!

**Comment by Mictronics** [comment]
Feel free. I am not a Python expert, more a beginner, and it's not my preferred language.
