### ISSUE TITLE
[How_to] which MQTT topic for sent text?

### ISSUE THREAD

**Issue by cnstudio** [Mictronics/meshtastic2hass#3]
I went to sent text from HASS to Meshtastic,
I use MQTT topic like below (from Meshtastic web site document)

topic: msh/2/json/mqtt/!67ea9400

but nothing happen, 
so, what MQTT topic is for sent text out?

And thank you for develop this project!  :)

**Comment by Mictronics** [comment]
Don't know. I just receive from Meshtastic into HASS but not vice versa.

**Comment by cnstudio** [comment]
I check Meshtastic documents, there are two different instructions of MQTT, newest one say the topic doesn't need nodeID.......

And this issue is about Meshtastic, not this project, so I'll close this issue,
sorry to bother you and thank you again.   :)
